### ISSUE TITLE
Eliminate all custom (non-Odysee) endpoints

### ISSUE THREAD

**Issue by kauffj** [lbryio/odysee-roku#12]

**Comment by s9260** [comment]
d0a3acaa3e9ac26ed2339fa21efacd6b7eb49cb8 (https://github.com/lbryio/odysee-roku/blob/d0a3acaa3e9ac26ed2339fa21efacd6b7eb49cb8/MVP-Roku/components/tasks/getConstants.brs) uses the desktop app github for determining the used endpoints. Is that considered a custom endpoint?
