### ISSUE TITLE
Vedio does not pay on odysee-roku

### ISSUE THREAD

**Issue by dfhepner** [lbryio/odysee-roku#15]
The last three videos of channel @FyNyth do not play on the roku app.  I believe she changed something in the way she encoded the videos starting Dec 30,2021.  The videos before that date work fine.

**Comment by s9260** [comment]
fixed in production with indev a79dfce03865c95f5f155d679000f434643c93cd

**Comment by s9260** [comment]
certain Odysee endpoints are slower, see [issue 13](https://github.com/OdyseeTeam/odysee-roku/issues/13) to see what i'm doing about it currently.

**Comment by dfhepner** [comment]
Thank-you.  I checked and it is working.
