### ISSUE TITLE
ensure install/new call works

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/odysee-roku#17]
https://github.com/OdyseeTeam/odysee-roku/blob/device-flow/MVP-Roku/components/tasks/rokuInstall.brs#L43

Doesn't seem to work today.

It can be called on startup -either with auth token, or later with the bearer token. 

We can fix the appid as: rokueecom692EAWhtoqDuAfQ6KHMXxFxt8tkhmt7sfprEMHWKjy5hf6PwZcHDV542V

**Comment by s9260** [comment]
should be fixed with bc6f340c22bb0629ae2e3811654238e3c2318aea
