### ISSUE TITLE
look into channel search issues

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/odysee-roku#33]
first report: @thequartering - no results

2nd report with feedback: I just tried searching for:
grizzly
grizzlypatriot
friesen
...in your current Roku app (v 1.0, build 7), but no results were found, even though the channel exists:

Mark Friesen *GrizzlyPatriot* *FFCS*
@GrizzlyPatriot

I then tried to click on the '*' button in the Roku remote on the Odyssee app launcher in order to 'Check for updates'. It then confirmed that 'Odysee has been updated' or 'Odysee channels have been updated'.
( By the way, room for improvement in design: I then had to click on ''Search Chann...' with a blank search field first in order to indicate to the app that I want to search for the previous 'grizzly' search term, which is awkward: the default is 'Search videos' so even going to grizzly and hitting 'ok' will search for videos first, not channels.)
Once I clicked on 'Search chann...' with a blank search field, the app knew that I wanted to search for a channel, and then I went on to search for the aforementioned search terms, and the channel was still not found.

**Comment by s9260** [comment]
eb52fff80563983667090f98f84521aeac75c6b3 should fix it if related to Array vs roArray. Also made the error more specific in case that doesn't fix it. Planning on pushing to device-flow as build 9 after I test SSO+API being down at the same time.
