### ISSUE TITLE
Go to the Following category on the left hand side and you'll be promoted to login.

### ISSUE THREAD

**Issue by robster7674** [lbryio/odysee-roku#39]
Go to the Following category on the left hand side and you'll be promoted to login.

_Originally posted by @tzarebczan in https://github.com/OdyseeTeam/odysee-roku/issues/38#issuecomment-1276112583_
      

In the unofficial app I do not have the "Following" category, and in the other Odysee app where I do have it, I eventually must use a USB security key to authenticate? I do not use a password to login normally, only username and authentication link. This option does not seem to be available in the Roku app?

Btw.: why are there two Odysee apps available? It is somewhat confusing.

**Comment by tzarebczan** [comment]
The original wasn't official and didn't have login, it's kept for legacy reasons.

On odysee, go to settings > password and setup a password. Then try the official app login again.

**Comment by robster7674** [comment]
> The original wasn't official and didn't have login, it's kept for legacy reasons.
> 
> On odysee, go to settings > password and setup a password. Then try the official app login again.

@tzarebczan : why did you close this without getting confirmation?

When I tried setting a password (which I actually don't want), I got an error message stating:
```
This account has been migrated to the odysee identity provider. Please navigate to https://accounts.odysee.com to manage your password there via the Single Sign On.
```
When I then went to Account Security > Signing In, I again got this message about registering a security key.

Why is logging in made so complicated, and in my case, impossible? What is this nonsense about a USB security key?

![image](https://user-images.githubusercontent.com/70331923/196022556-7131ebde-d732-4204-9b1b-4f5b5d8f327f.png)

**Comment by tzarebczan** [comment]
This isn't a support system. Email hello@odysee.com to get them disconnected so you can setup a password. There's no way to do it otherwise at the moment.
