### ISSUE TITLE
Vidio title on retrieving / video player screens

### ISSUE THREAD

**Issue by iamflorencejay** [lbryio/odysee-roku#9]
When I pause, there's no video title on the bottom of the progress bar screen for some reason.

**Comment by s9260** [comment]
I'm actually planning on entirely replacing the Video UI once I start the actual refactor, so this won't apply eventually.

**Comment by iamflorencejay** [comment]
NOICE

**Comment by s9260** [comment]
fixed indev d0a3acaa3e9ac26ed2339fa21efacd6b7eb49cb8

**Comment by iamflorencejay** [comment]
POG
